# Esercizio

Data la matrice di transizione
<br>
\begin{bmatrix}
0 & \frac{1}{4} & \frac{3}{4} \\
0 & \frac{1}{2} & \frac{1}{2} \\
\frac{3}{4} & 0 & \frac{1}{4} \\
\end{bmatrix}
<br>
dimostrare che ha un’unica distribuzione stazionaria π e determinarla sia analiticamente che con
il metodo Monte Carlo confrontando infine i risultati.
<br>

### Definiamo gli stati comunicanti
- 1->2, 1->3
- 2->2, 2->3
- 3->1, 3->3

Per transitività 3->2 quindi tutti gli stati comunicano tra loro, quindi la catena è **irriducibile**.<br>
Inoltre p_22 e p_33 sono > 0 (essendoci almeno un elemento non nullo nella diagonale principale), quindi per il criterio di regolarità essa è **regolare**.<br>

### Criterio di regolarità
D'altra parte la catena è irriducibile e almeno un elemento nella diagonale è positivo. Quindi esiste un'unica distribuzione stazionaria.<br>

### Teorema di Markov
Per il teorema di Markov la catena ha un'unica distribuzione stazionaria dato che P è **regolare** .<br>

In [6]:
import numpy as np

P = np.array([
    [0, 1/4, 3/4],
    [0, 1/2, 1/2],
    [3/4, 0, 1/4]
])

print(f'Matrice P^2: \n{np.dot(P,P)}\n')
print('Ha tutti valori positivi, per tanto P è regolare per definizione (ulteriore prova)')

Matrice P^2: 
[[0.5625 0.125  0.3125]
 [0.375  0.25   0.375 ]
 [0.1875 0.1875 0.625 ]]

Ha tutti valori positivi, per tanto P è regolare per definizione (ulteriore prova)


## Metodo algebrico

In [46]:
lam, V = np.linalg.eig(P.T) # Trasposta perchè voglio i sinistri

print(f'Autovalori: {lam}\n')
print(f'Matrice le cui colonne dono gli autovettori: \n{V}\n')

# Per la distribuzione stazionaria prendo la colonna corrispondente all'autovalore 1 (la seconda)

v = V[:,1]/np.sum(V[:,1]) # divido per la somma perchè voglio normalizzare
print(f'Distribuzione stazionaria: {v}')

Autovalori: [-0.57569391  1.          0.32569391]

Matrice le cui colonne dono gli autovettori: 
[[ 0.78010553 -0.57469577  0.55506939]
 [-0.18130286 -0.28734789 -0.79611302]
 [-0.59880267 -0.76626103  0.24104363]]

Distribuzione stazionaria: [0.35294118 0.17647059 0.47058824]


## Metodo Monte Carlo

In [53]:
n = 3 # dimensione della matrice
F = np.zeros(n)
j = np.random.randint(n) # da zero a n-1
F[j] = 1
N = 100
for i in range(N):
    j_multi = np.random.multinomial(1, P[j,:])
    j = np.nonzero(j_multi)[0][0]
    F[j] += 1
v= F/N # per avere le probabilità
print(f'Distribuzione stazionaria: {v}')

Distribuzione stazionaria: [0.36 0.16 0.49]
