In [1]:
# Librerie 

import numpy as np
import matplotlib.pyplot as plt

### Matrice di transizione e regolarità

In [2]:
P = np.array([[0, 1/3, 0, 1/3, 1/3],
              [1/3, 0, 1/3, 0, 1/3],
              [0, 1/3, 0, 1/3, 1/3],
              [1/3, 0, 1/3, 0, 1/3],
              [1/4, 1/4, 1/4, 1/4, 0]]) 

print(f'Matrice di transizione: \n{P}\n')
print(f'Matrice di transizione al passo 2: \n{P@P}\n')

# Avendo tutti valori non nulli al passo 2, P è regolare
# Come ulteriore prova si ha che ogni stato comunica con ogni altro

Matrice di transizione: 
[[0.         0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.         0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.25       0.25       0.25       0.25       0.        ]]

Matrice di transizione al passo 2: 
[[0.30555556 0.08333333 0.30555556 0.08333333 0.22222222]
 [0.08333333 0.30555556 0.08333333 0.30555556 0.22222222]
 [0.30555556 0.08333333 0.30555556 0.08333333 0.22222222]
 [0.08333333 0.30555556 0.08333333 0.30555556 0.22222222]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.33333333]]



### Metodo algebrico

In [3]:
lam, V = np.linalg.eig(P.T)

print(f'Autovalori: \n{np.round(np.real(lam),2)}\n')
print(f'Matrice le cui colonne sono gli autovettori: \n{np.round(np.real(V), 2)}\n')

v = V[:,0]/np.sum(V[:,0])
print(f'Distribuzione stazionaria: {np.round(np.real(v), 2)}')

Autovalori: 
[ 1.   -0.67 -0.33  0.    0.  ]

Matrice le cui colonne sono gli autovettori: 
[[ 0.42  0.5   0.22  0.16  0.16]
 [ 0.42 -0.5   0.22 -0.66 -0.66]
 [ 0.42  0.5   0.22 -0.16 -0.16]
 [ 0.42 -0.5   0.22  0.66  0.66]
 [ 0.55 -0.   -0.89  0.    0.  ]]

Distribuzione stazionaria: [0.19 0.19 0.19 0.19 0.25]


### Metodo Monte Carlo

In [5]:
n = P[0].size
F = np.zeros(n)
N = 100000

j = np.random.randint(0, n)
F[j] = 1

for i in range(N):
    multi = np.random.multinomial(1, P[j])
    j = np.nonzero(multi)[0][0]
    F[j] += 1
    
v = F/N
print(f'Distribuzione stazionaria: {np.round(np.real(v), 2)}')

Distribuzione stazionaria: [0.19 0.19 0.19 0.19 0.25]
