# Esercizio

Data la matrice di transizione
<br>
\begin{bmatrix}
0 & \frac{1}{4} & \frac{3}{4} \\
0 & \frac{1}{2} & \frac{1}{2} \\
\frac{3}{4} & 0 & \frac{1}{4} \\
\end{bmatrix}
<br>
- Dimostrare che ha un’unica distribuzione stazionaria **$\pi$** ;
- Determinarla analiticamente ;
- Determinarla con il metodo Monte Carlo e confrontare i risultati ottenuti ;

# Punto 1

Allo stato attuale abbiamo i seguenti stati comunicanti:

- 1->2, 1->3<br>
- 2->2, 2->3<br>
- 3->1, 3->3<br>

Per transisitività si ha che anche i seguenti stati sono comunicanti:

- 1->1 (poichè 1->3 e 3->1)<br>
- 2->1 (poichè 2->3 e 3->1)<br>
- 3->2 (poichè 3->1 e 1->2)<br>

Dato che tutti gli stati comunicano tra loro P si dice **irriducibile**.

Possiamo anche verificare che P sia **irriducibile** come segue:

In [1]:
import numpy as np

P = np.array([
    [0, 1/4, 3/4],
    [0, 1/2, 1/2],
    [3/4, 0, 1/4]
])

print(f'Matrice di transizione: \n\n{P}\n')
print(f'Matrice di transizione al passo 2: \n\n{np.dot(P, P)}\n')
print('Poichè la matrice di transizione al passo 2 ha tutti valori positivi, essa sarà irriducibile')

Matrice di transizione: 

[[0.   0.25 0.75]
 [0.   0.5  0.5 ]
 [0.75 0.   0.25]]

Matrice di transizione al passo 2: 

[[0.5625 0.125  0.3125]
 [0.375  0.25   0.375 ]
 [0.1875 0.1875 0.625 ]]

Poichè la matrice di transizione al passo 2 ha tutti valori positivi, essa sarà irriducibile


Vale la seguente

### **Proprietà** : 

#### se P è irriducibile ed E è finito, allora la distribuzione stazionaria $\pi$ è unica

Possiamo inoltre affermare che P è regolare poichè vale il seguente

### Criterio di regolarità :

#### se P è irriducibile ed almeno un elemento nella diagonale principale risulta > 0, allora P è regolare

# Punto 2 

## Metodo Algebrico

In [2]:
# eigenvalues restituisce una tupla contenente un array degli autovalori e una matrice degli autovettori.
lam, V = np.linalg.eig(P.T) # P è trasposta perchè voglio gli autovettori sinistri

print(f'Autovalori: {lam}\n')
print(f'Matrice le cui colonne sono gli autovettori: \n\n{V}\n')

# Per la distribuzione stazionaria prendo la colonna corrispondente all'autovalore 1 (la seconda)
v = V[:,1]
N = np.sum(V[:,1])
v/=N # normalizzo
print(f'Distribuzione stazionaria: {np.round(v, 3)}')

Autovalori: [-0.57569391  1.          0.32569391]

Matrice le cui colonne sono gli autovettori: 

[[ 0.78010553 -0.57469577  0.55506939]
 [-0.18130286 -0.28734789 -0.79611302]
 [-0.59880267 -0.76626103  0.24104363]]

Distribuzione stazionaria: [0.353 0.176 0.471]


# Punto 3

## Metodo Monte Carlo

In [3]:
n = np.size(P[0]) # dimensione di E
F = np.zeros(n) # Vettore della frequeza di realizzazione degli stati di E

N = 10000
j0 = np.random.randint(0, n) # Step 1
F[j0] = 1

for i in range(N):
    jk = np.random.multinomial(1, P[j0,:]) # Step 2
    j0 = np.nonzero(jk)[0][0]
    F[j0] += 1

v = F/N # normalizzo per ottenere le probabilità dalle frequenze
print(f'Distribuzione stazionaria: {v}')

Distribuzione stazionaria: [0.3516 0.1762 0.4723]
